image: kitproject/gitpod-flutter:v2.5.0
tasks:
  - init: >
      flutter pub get
    command: >
      flutter run --debug -d web-server --web-port=8080 --web-hostname=0.0.0.0 --target="lib/main_web.dart" -v
ports:
  - port: 8080
    onOpen: open-preview
